# Generated by Django 3.2.9 on 2021-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('authors', models.CharField(max_length=256)),
                ('published_date', models.CharField(default=1900, max_length=20)),
                ('isbn_10', models.CharField(blank=True, max_length=256, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=256, null=True)),
                ('page_count', models.IntegerField(blank=True, default=0, null=True)),
                ('image_links', models.CharField(blank=True, max_length=1024, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
